### ISSUE TITLE
Migrate repo to samplchallenges org?

### ISSUE THREAD

**Issue by jchodera** [samplchallenges/SAMPL6#91]
We may want to migrate this repo to https://github.com/samplchallenges so that all the data can easily be found together.

GitHub will leave a link in place to automatically redirect from https://github.com/mobleylab/sampl6 to https://github.com/mobleylab/samplchallenges (as long as nobody creates a new `sampl6` repo), and I think we've already archived the releases on Zenodo with a DOI attached.

**Comment by MehtapIsik** [comment]
I think we shouldn't move the SAMPL6 repo. Previous publications of SAMPL6 challenges are pointing to [https://github.com/mobleylab/sampl6](https://github.com/mobleylab/sampl6). I think it is more important to preserve these links.

Future repositories like SAMPL7 repo can be moved to https://github.com/mobleylab/samplchallenges  and we can put a clone of SAMPL6 repo there once we are done with it. But I am still working on pKa and logP sections of SAMPL6 repo, so we are not there yet.

**Comment by jchodera** [comment]
The old link will still work---it will redirect to the new location.

**Comment by davidlmobley** [comment]
I didn't see that the cost-benefit ratio for having to migrate all of the old challenges from `mobleylab` to `samplchallenges` was worth it (it'll presumably take an hour or two to move all the repos and change all the links so that Google will update, whereas I doubt many people arrive at the repos by trying to navigate directly via URL).

**Comment by jchodera** [comment]
> change all the links so that Google will update

There's no need to change links---they will automatically be redirected.

The benefit would be that http://github.com/samplchallenges will become a landing page that contains version-controlled datasets for all historical SAMPL data, which is part of our curation responsibility as part of the grant. Sorting through http://github.com/mobleylab to find datasets is not so fun.

**Comment by davidlmobley** [comment]
OK, good idea.
