### ISSUE TITLE
SAMPLing challenge instructions link broken?

### ISSUE THREAD

**Issue by jchodera** [samplchallenges/SAMPL6#96]
On [this page](https://github.com/samplchallenges/SAMPL6/tree/master/host_guest/SAMPLing) the `README.md` contains a link to the SAMPLing instructions that is broken:
![image](https://user-images.githubusercontent.com/3656088/71908466-1185c680-313c-11ea-93da-7028aa2a63d2.png)

The link is https://github.com/samplchallenges/SAMPL6/blob/master/host_guest/SAMPLing_instructions.md#files-description

I can't figure out where this may have gone. Any ideas?

**Comment by davidlmobley** [comment]
Resolved by #100 ; it was at the base level rather than in a subdirectory.
